BEGIN;
--
-- Create model Permiso
--
CREATE TABLE "accounts_permiso" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nombre" varchar(255) NOT NULL UNIQUE);
--
-- Create model Rol
--
CREATE TABLE "accounts_rol" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nombre" varchar(50) NOT NULL UNIQUE);
CREATE TABLE "accounts_rol_permisos" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "rol_id" bigint NOT NULL, "permiso_id" bigint NOT NULL);
--
-- Create model Usuario
--
CREATE TABLE "accounts_usuario" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "avatar" varchar(200) NULL, "email" varchar(254) NOT NULL UNIQUE, "nombre" varchar(255) NOT NULL);
CREATE TABLE "accounts_usuario_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "usuario_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "accounts_usuario_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "usuario_id" bigint NOT NULL, "permission_id" integer NOT NULL);
CREATE TABLE "accounts_usuario_roles" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "usuario_id" bigint NOT NULL, "rol_id" bigint NOT NULL);
CREATE INDEX "accounts_permiso_nombre_c55deb6c_like" ON "accounts_permiso" ("nombre" varchar_pattern_ops);
CREATE INDEX "accounts_rol_nombre_54c22e50_like" ON "accounts_rol" ("nombre" varchar_pattern_ops);
ALTER TABLE "accounts_rol_permisos" ADD CONSTRAINT "accounts_rol_permisos_rol_id_permiso_id_9f2fc31c_uniq" UNIQUE ("rol_id", "permiso_id");
ALTER TABLE "accounts_rol_permisos" ADD CONSTRAINT "accounts_rol_permisos_rol_id_2f3ce0a4_fk_accounts_rol_id" FOREIGN KEY ("rol_id") REFERENCES "accounts_rol" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_rol_permisos" ADD CONSTRAINT "accounts_rol_permiso_permiso_id_5b489a34_fk_accounts_" FOREIGN KEY ("permiso_id") REFERENCES "accounts_permiso" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_rol_permisos_rol_id_2f3ce0a4" ON "accounts_rol_permisos" ("rol_id");
CREATE INDEX "accounts_rol_permisos_permiso_id_5b489a34" ON "accounts_rol_permisos" ("permiso_id");
CREATE INDEX "accounts_usuario_email_19c7414e_like" ON "accounts_usuario" ("email" varchar_pattern_ops);
ALTER TABLE "accounts_usuario_groups" ADD CONSTRAINT "accounts_usuario_groups_usuario_id_group_id_90f476d3_uniq" UNIQUE ("usuario_id", "group_id");
ALTER TABLE "accounts_usuario_groups" ADD CONSTRAINT "accounts_usuario_gro_usuario_id_8eb16911_fk_accounts_" FOREIGN KEY ("usuario_id") REFERENCES "accounts_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_usuario_groups" ADD CONSTRAINT "accounts_usuario_groups_group_id_81d91a41_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_usuario_groups_usuario_id_8eb16911" ON "accounts_usuario_groups" ("usuario_id");
CREATE INDEX "accounts_usuario_groups_group_id_81d91a41" ON "accounts_usuario_groups" ("group_id");
ALTER TABLE "accounts_usuario_user_permissions" ADD CONSTRAINT "accounts_usuario_user_pe_usuario_id_permission_id_0065a2ce_uniq" UNIQUE ("usuario_id", "permission_id");
ALTER TABLE "accounts_usuario_user_permissions" ADD CONSTRAINT "accounts_usuario_use_usuario_id_d048ad71_fk_accounts_" FOREIGN KEY ("usuario_id") REFERENCES "accounts_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_usuario_user_permissions" ADD CONSTRAINT "accounts_usuario_use_permission_id_3de42c14_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_usuario_user_permissions_usuario_id_d048ad71" ON "accounts_usuario_user_permissions" ("usuario_id");
CREATE INDEX "accounts_usuario_user_permissions_permission_id_3de42c14" ON "accounts_usuario_user_permissions" ("permission_id");
ALTER TABLE "accounts_usuario_roles" ADD CONSTRAINT "accounts_usuario_roles_usuario_id_rol_id_ea6fe026_uniq" UNIQUE ("usuario_id", "rol_id");
ALTER TABLE "accounts_usuario_roles" ADD CONSTRAINT "accounts_usuario_rol_usuario_id_3d21e6bb_fk_accounts_" FOREIGN KEY ("usuario_id") REFERENCES "accounts_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_usuario_roles" ADD CONSTRAINT "accounts_usuario_roles_rol_id_d12cdecc_fk_accounts_rol_id" FOREIGN KEY ("rol_id") REFERENCES "accounts_rol" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_usuario_roles_usuario_id_3d21e6bb" ON "accounts_usuario_roles" ("usuario_id");
CREATE INDEX "accounts_usuario_roles_rol_id_d12cdecc" ON "accounts_usuario_roles" ("rol_id");
COMMIT;
