--
-- PostgreSQL database dump
--

\restrict YVMAxB0octaTqmXrkKbnkQmbwbIuukxWTOTpsC6ZzJpE3axDe4GcKuBiO2jWNIw

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: 123; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA "123";


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_usuario (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    avatar character varying(200),
    email character varying(254) NOT NULL,
    nombre character varying(255) NOT NULL
);


--
-- Name: accounts_usuario_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_usuario_groups (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: accounts_usuario_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_usuario_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_usuario_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_usuario_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_usuario_roles (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    rol_id bigint NOT NULL
);


--
-- Name: accounts_usuario_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_usuario_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_usuario_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_usuario_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_usuario_user_permissions (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: accounts_usuario_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_usuario_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_usuario_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auditoria_registroactividad; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auditoria_registroactividad (
    id bigint NOT NULL,
    accion character varying(20) NOT NULL,
    descripcion text NOT NULL,
    detalles jsonb,
    ip_address inet,
    user_agent text NOT NULL,
    fecha timestamp with time zone NOT NULL,
    usuario_id bigint
);


--
-- Name: auditoria_registroactividad_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auditoria_registroactividad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auditoria_registroactividad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: casos_de_uso_casodeuso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.casos_de_uso_casodeuso (
    id bigint NOT NULL,
    nombre character varying(255) NOT NULL,
    descripcion text NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    creado_por_id bigint,
    proyecto_id bigint NOT NULL,
    detalle_agil_id bigint,
    detalle_tradicional_id bigint,
    imagen character varying(100),
    link_externo character varying(500) NOT NULL
);


--
-- Name: casos_de_uso_casodeuso_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.casos_de_uso_casodeuso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.casos_de_uso_casodeuso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: casos_de_uso_detallecasodeusoagil; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.casos_de_uso_detallecasodeusoagil (
    id bigint NOT NULL,
    historia_usuario text NOT NULL,
    criterio_aceptacion text NOT NULL,
    responsable character varying(100) NOT NULL,
    estado_scrum character varying(100) NOT NULL,
    observaciones text NOT NULL,
    caso_de_uso_padre_id bigint NOT NULL
);


--
-- Name: casos_de_uso_detallecasodeusoagil_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.casos_de_uso_detallecasodeusoagil ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.casos_de_uso_detallecasodeusoagil_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: casos_de_uso_detallecasodeusotradicional; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.casos_de_uso_detallecasodeusotradicional (
    id bigint NOT NULL,
    actor_principal character varying(255) NOT NULL,
    precondiciones text NOT NULL,
    flujo_principal text NOT NULL,
    flujo_alternativo text NOT NULL,
    postcondiciones text NOT NULL,
    observaciones text NOT NULL,
    caso_de_uso_padre_id bigint NOT NULL
);


--
-- Name: casos_de_uso_detallecasodeusotradicional_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.casos_de_uso_detallecasodeusotradicional ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.casos_de_uso_detallecasodeusotradicional_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: casos_de_uso_historicalcasodeuso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.casos_de_uso_historicalcasodeuso (
    id bigint NOT NULL,
    nombre character varying(255) NOT NULL,
    descripcion text NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    imagen text,
    link_externo character varying(500) NOT NULL,
    history_id integer NOT NULL,
    history_date timestamp with time zone NOT NULL,
    history_change_reason character varying(100),
    history_type character varying(1) NOT NULL,
    creado_por_id bigint,
    detalle_agil_id bigint,
    detalle_tradicional_id bigint,
    history_user_id bigint,
    proyecto_id bigint
);


--
-- Name: casos_de_uso_historicalcasodeuso_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.casos_de_uso_historicalcasodeuso ALTER COLUMN history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.casos_de_uso_historicalcasodeuso_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: grupos_grupo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.grupos_grupo (
    id bigint NOT NULL,
    nombre character varying(255) NOT NULL,
    logo character varying(100),
    fecha_creacion timestamp with time zone NOT NULL,
    activo boolean NOT NULL,
    creado_por_id bigint,
    lider_id bigint
);


--
-- Name: grupos_grupo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.grupos_grupo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grupos_grupo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grupos_grupo_integrantes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.grupos_grupo_integrantes (
    id bigint NOT NULL,
    grupo_id bigint NOT NULL,
    usuario_id bigint NOT NULL
);


--
-- Name: grupos_grupo_integrantes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.grupos_grupo_integrantes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grupos_grupo_integrantes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permisos_permiso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permisos_permiso (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);


--
-- Name: permisos_permiso_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.permisos_permiso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permisos_permiso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proyectos_historicalproyecto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proyectos_historicalproyecto (
    id bigint NOT NULL,
    nombre character varying(200) NOT NULL,
    descripcion text,
    metodologia character varying(20),
    fecha_creacion timestamp with time zone NOT NULL,
    activo boolean NOT NULL,
    logo text,
    history_id integer NOT NULL,
    history_date timestamp with time zone NOT NULL,
    history_change_reason character varying(100),
    history_type character varying(1) NOT NULL,
    creado_por_id bigint,
    grupo_id bigint,
    history_user_id bigint,
    lider_id bigint
);


--
-- Name: proyectos_historicalproyecto_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.proyectos_historicalproyecto ALTER COLUMN history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proyectos_historicalproyecto_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proyectos_participacionproyecto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proyectos_participacionproyecto (
    id bigint NOT NULL,
    fecha_asignacion timestamp with time zone NOT NULL,
    rol_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    proyecto_id bigint NOT NULL
);


--
-- Name: proyectos_participacionproyecto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.proyectos_participacionproyecto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proyectos_participacionproyecto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proyectos_proyecto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proyectos_proyecto (
    id bigint NOT NULL,
    nombre character varying(200) NOT NULL,
    descripcion text,
    metodologia character varying(20),
    fecha_creacion timestamp with time zone NOT NULL,
    activo boolean NOT NULL,
    lider_id bigint,
    creado_por_id bigint,
    logo character varying(100),
    grupo_id bigint
);


--
-- Name: proyectos_proyecto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.proyectos_proyecto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proyectos_proyecto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: requerimientos_detallerequerimientoagil; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.requerimientos_detallerequerimientoagil (
    id bigint NOT NULL,
    historia_usuario text NOT NULL,
    criterio_aceptacion text NOT NULL,
    puntos_estimados integer,
    sprint_asignado character varying(100) NOT NULL,
    responsable character varying(100) NOT NULL,
    estado_scrum character varying(100) NOT NULL,
    observaciones text NOT NULL,
    requerimiento_padre_id bigint NOT NULL,
    CONSTRAINT requerimientos_detallerequerimientoagil_puntos_estimados_check CHECK ((puntos_estimados >= 0))
);


--
-- Name: requerimientos_detallerequerimientoagil_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.requerimientos_detallerequerimientoagil ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.requerimientos_detallerequerimientoagil_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: requerimientos_detallerequerimientotradicional; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.requerimientos_detallerequerimientotradicional (
    id bigint NOT NULL,
    prioridad character varying(50) NOT NULL,
    fuente character varying(255) NOT NULL,
    categoria character varying(100) NOT NULL,
    fecha_compromiso date,
    estado_validacion character varying(100) NOT NULL,
    observaciones text NOT NULL,
    requerimiento_padre_id bigint NOT NULL
);


--
-- Name: requerimientos_detallerequerimientotradicional_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.requerimientos_detallerequerimientotradicional ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.requerimientos_detallerequerimientotradicional_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: requerimientos_historicalrequerimiento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.requerimientos_historicalrequerimiento (
    id bigint NOT NULL,
    nombre character varying(255) NOT NULL,
    descripcion text NOT NULL,
    tipo character varying(20) NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    imagen text,
    link_externo character varying(500) NOT NULL,
    history_id integer NOT NULL,
    history_date timestamp with time zone NOT NULL,
    history_change_reason character varying(100),
    history_type character varying(1) NOT NULL,
    creado_por_id bigint,
    detalle_agil_id bigint,
    detalle_tradicional_id bigint,
    history_user_id bigint,
    proyecto_id bigint
);


--
-- Name: requerimientos_historicalrequerimiento_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.requerimientos_historicalrequerimiento ALTER COLUMN history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.requerimientos_historicalrequerimiento_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: requerimientos_requerimiento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.requerimientos_requerimiento (
    id bigint NOT NULL,
    nombre character varying(255) NOT NULL,
    descripcion text NOT NULL,
    tipo character varying(20) NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    creado_por_id bigint,
    detalle_agil_id bigint,
    detalle_tradicional_id bigint,
    proyecto_id bigint NOT NULL,
    imagen character varying(100),
    link_externo character varying(500) NOT NULL
);


--
-- Name: requerimientos_requerimiento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.requerimientos_requerimiento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.requerimientos_requerimiento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: requerimientos_requerimientocaso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.requerimientos_requerimientocaso (
    id bigint NOT NULL,
    fecha_vinculacion timestamp with time zone NOT NULL,
    nota character varying(255) NOT NULL,
    caso_de_uso_id bigint NOT NULL,
    requerimiento_id bigint NOT NULL
);


--
-- Name: requerimientos_requerimientocaso_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.requerimientos_requerimientocaso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.requerimientos_requerimientocaso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles_rol; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles_rol (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    color character varying(7) NOT NULL,
    icono_url character varying(200)
);


--
-- Name: roles_rol_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles_rol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles_rol_permisos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles_rol_permisos (
    id bigint NOT NULL,
    rol_id bigint NOT NULL,
    permiso_id bigint NOT NULL
);


--
-- Name: roles_rol_permisos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles_rol_permisos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_rol_permisos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_usuario accounts_usuario_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_usuario
    ADD CONSTRAINT accounts_usuario_email_key UNIQUE (email);


--
-- Name: accounts_usuario_groups accounts_usuario_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_usuario_groups
    ADD CONSTRAINT accounts_usuario_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_usuario_groups accounts_usuario_groups_usuario_id_group_id_90f476d3_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_usuario_groups
    ADD CONSTRAINT accounts_usuario_groups_usuario_id_group_id_90f476d3_uniq UNIQUE (usuario_id, group_id);


--
-- Name: accounts_usuario accounts_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_usuario
    ADD CONSTRAINT accounts_usuario_pkey PRIMARY KEY (id);


--
-- Name: accounts_usuario_roles accounts_usuario_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_usuario_roles
    ADD CONSTRAINT accounts_usuario_roles_pkey PRIMARY KEY (id);


--
-- Name: accounts_usuario_roles accounts_usuario_roles_usuario_id_rol_id_ea6fe026_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_usuario_roles
    ADD CONSTRAINT accounts_usuario_roles_usuario_id_rol_id_ea6fe026_uniq UNIQUE (usuario_id, rol_id);


--
-- Name: accounts_usuario_user_permissions accounts_usuario_user_pe_usuario_id_permission_id_0065a2ce_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_usuario_user_permissions
    ADD CONSTRAINT accounts_usuario_user_pe_usuario_id_permission_id_0065a2ce_uniq UNIQUE (usuario_id, permission_id);


--
-- Name: accounts_usuario_user_permissions accounts_usuario_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_usuario_user_permissions
    ADD CONSTRAINT accounts_usuario_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auditoria_registroactividad auditoria_registroactividad_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria_registroactividad
    ADD CONSTRAINT auditoria_registroactividad_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: casos_de_uso_casodeuso casos_de_uso_casodeuso_detalle_agil_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.casos_de_uso_casodeuso
    ADD CONSTRAINT casos_de_uso_casodeuso_detalle_agil_id_key UNIQUE (detalle_agil_id);


--
-- Name: casos_de_uso_casodeuso casos_de_uso_casodeuso_detalle_tradicional_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.casos_de_uso_casodeuso
    ADD CONSTRAINT casos_de_uso_casodeuso_detalle_tradicional_id_key UNIQUE (detalle_tradicional_id);


--
-- Name: casos_de_uso_casodeuso casos_de_uso_casodeuso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.casos_de_uso_casodeuso
    ADD CONSTRAINT casos_de_uso_casodeuso_pkey PRIMARY KEY (id);


--
-- Name: casos_de_uso_detallecasodeusoagil casos_de_uso_detallecasodeusoagil_caso_de_uso_padre_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.casos_de_uso_detallecasodeusoagil
    ADD CONSTRAINT casos_de_uso_detallecasodeusoagil_caso_de_uso_padre_id_key UNIQUE (caso_de_uso_padre_id);


--
-- Name: casos_de_uso_detallecasodeusoagil casos_de_uso_detallecasodeusoagil_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.casos_de_uso_detallecasodeusoagil
    ADD CONSTRAINT casos_de_uso_detallecasodeusoagil_pkey PRIMARY KEY (id);


--
-- Name: casos_de_uso_detallecasodeusotradicional casos_de_uso_detallecasodeusotradicion_caso_de_uso_padre_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.casos_de_uso_detallecasodeusotradicional
    ADD CONSTRAINT casos_de_uso_detallecasodeusotradicion_caso_de_uso_padre_id_key UNIQUE (caso_de_uso_padre_id);


--
-- Name: casos_de_uso_detallecasodeusotradicional casos_de_uso_detallecasodeusotradicional_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.casos_de_uso_detallecasodeusotradicional
    ADD CONSTRAINT casos_de_uso_detallecasodeusotradicional_pkey PRIMARY KEY (id);


--
-- Name: casos_de_uso_historicalcasodeuso casos_de_uso_historicalcasodeuso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.casos_de_uso_historicalcasodeuso
    ADD CONSTRAINT casos_de_uso_historicalcasodeuso_pkey PRIMARY KEY (history_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: grupos_grupo_integrantes grupos_grupo_integrantes_grupo_id_usuario_id_b506e5a1_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grupos_grupo_integrantes
    ADD CONSTRAINT grupos_grupo_integrantes_grupo_id_usuario_id_b506e5a1_uniq UNIQUE (grupo_id, usuario_id);


--
-- Name: grupos_grupo_integrantes grupos_grupo_integrantes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grupos_grupo_integrantes
    ADD CONSTRAINT grupos_grupo_integrantes_pkey PRIMARY KEY (id);


--
-- Name: grupos_grupo grupos_grupo_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grupos_grupo
    ADD CONSTRAINT grupos_grupo_nombre_key UNIQUE (nombre);


--
-- Name: grupos_grupo grupos_grupo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grupos_grupo
    ADD CONSTRAINT grupos_grupo_pkey PRIMARY KEY (id);


--
-- Name: permisos_permiso permisos_permiso_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permisos_permiso
    ADD CONSTRAINT permisos_permiso_nombre_key UNIQUE (nombre);


--
-- Name: permisos_permiso permisos_permiso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permisos_permiso
    ADD CONSTRAINT permisos_permiso_pkey PRIMARY KEY (id);


--
-- Name: proyectos_historicalproyecto proyectos_historicalproyecto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos_historicalproyecto
    ADD CONSTRAINT proyectos_historicalproyecto_pkey PRIMARY KEY (history_id);


--
-- Name: proyectos_participacionproyecto proyectos_participacionp_usuario_id_proyecto_id_7d795bbd_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos_participacionproyecto
    ADD CONSTRAINT proyectos_participacionp_usuario_id_proyecto_id_7d795bbd_uniq UNIQUE (usuario_id, proyecto_id);


--
-- Name: proyectos_participacionproyecto proyectos_participacionproyecto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos_participacionproyecto
    ADD CONSTRAINT proyectos_participacionproyecto_pkey PRIMARY KEY (id);


--
-- Name: proyectos_proyecto proyectos_proyecto_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos_proyecto
    ADD CONSTRAINT proyectos_proyecto_nombre_key UNIQUE (nombre);


--
-- Name: proyectos_proyecto proyectos_proyecto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos_proyecto
    ADD CONSTRAINT proyectos_proyecto_pkey PRIMARY KEY (id);


--
-- Name: requerimientos_detallerequerimientoagil requerimientos_detallerequerimientoa_requerimiento_padre_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_detallerequerimientoagil
    ADD CONSTRAINT requerimientos_detallerequerimientoa_requerimiento_padre_id_key UNIQUE (requerimiento_padre_id);


--
-- Name: requerimientos_detallerequerimientoagil requerimientos_detallerequerimientoagil_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_detallerequerimientoagil
    ADD CONSTRAINT requerimientos_detallerequerimientoagil_pkey PRIMARY KEY (id);


--
-- Name: requerimientos_detallerequerimientotradicional requerimientos_detallerequerimientot_requerimiento_padre_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_detallerequerimientotradicional
    ADD CONSTRAINT requerimientos_detallerequerimientot_requerimiento_padre_id_key UNIQUE (requerimiento_padre_id);


--
-- Name: requerimientos_detallerequerimientotradicional requerimientos_detallerequerimientotradicional_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_detallerequerimientotradicional
    ADD CONSTRAINT requerimientos_detallerequerimientotradicional_pkey PRIMARY KEY (id);


--
-- Name: requerimientos_historicalrequerimiento requerimientos_historicalrequerimiento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_historicalrequerimiento
    ADD CONSTRAINT requerimientos_historicalrequerimiento_pkey PRIMARY KEY (history_id);


--
-- Name: requerimientos_requerimientocaso requerimientos_requerimi_requerimiento_id_caso_de_752f076f_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_requerimientocaso
    ADD CONSTRAINT requerimientos_requerimi_requerimiento_id_caso_de_752f076f_uniq UNIQUE (requerimiento_id, caso_de_uso_id);


--
-- Name: requerimientos_requerimiento requerimientos_requerimiento_detalle_agil_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_requerimiento
    ADD CONSTRAINT requerimientos_requerimiento_detalle_agil_id_key UNIQUE (detalle_agil_id);


--
-- Name: requerimientos_requerimiento requerimientos_requerimiento_detalle_tradicional_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_requerimiento
    ADD CONSTRAINT requerimientos_requerimiento_detalle_tradicional_id_key UNIQUE (detalle_tradicional_id);


--
-- Name: requerimientos_requerimiento requerimientos_requerimiento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_requerimiento
    ADD CONSTRAINT requerimientos_requerimiento_pkey PRIMARY KEY (id);


--
-- Name: requerimientos_requerimientocaso requerimientos_requerimientocaso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_requerimientocaso
    ADD CONSTRAINT requerimientos_requerimientocaso_pkey PRIMARY KEY (id);


--
-- Name: roles_rol roles_rol_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_rol
    ADD CONSTRAINT roles_rol_nombre_key UNIQUE (nombre);


--
-- Name: roles_rol_permisos roles_rol_permisos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_rol_permisos
    ADD CONSTRAINT roles_rol_permisos_pkey PRIMARY KEY (id);


--
-- Name: roles_rol_permisos roles_rol_permisos_rol_id_permiso_id_8cc19402_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_rol_permisos
    ADD CONSTRAINT roles_rol_permisos_rol_id_permiso_id_8cc19402_uniq UNIQUE (rol_id, permiso_id);


--
-- Name: roles_rol roles_rol_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_rol
    ADD CONSTRAINT roles_rol_pkey PRIMARY KEY (id);


--
-- Name: accounts_usuario_email_19c7414e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_usuario_email_19c7414e_like ON public.accounts_usuario USING btree (email varchar_pattern_ops);


--
-- Name: accounts_usuario_groups_group_id_81d91a41; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_usuario_groups_group_id_81d91a41 ON public.accounts_usuario_groups USING btree (group_id);


--
-- Name: accounts_usuario_groups_usuario_id_8eb16911; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_usuario_groups_usuario_id_8eb16911 ON public.accounts_usuario_groups USING btree (usuario_id);


--
-- Name: accounts_usuario_nombre_24ef34b9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_usuario_nombre_24ef34b9 ON public.accounts_usuario USING btree (nombre);


--
-- Name: accounts_usuario_nombre_24ef34b9_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_usuario_nombre_24ef34b9_like ON public.accounts_usuario USING btree (nombre varchar_pattern_ops);


--
-- Name: accounts_usuario_roles_rol_id_d12cdecc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_usuario_roles_rol_id_d12cdecc ON public.accounts_usuario_roles USING btree (rol_id);


--
-- Name: accounts_usuario_roles_usuario_id_3d21e6bb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_usuario_roles_usuario_id_3d21e6bb ON public.accounts_usuario_roles USING btree (usuario_id);


--
-- Name: accounts_usuario_user_permissions_permission_id_3de42c14; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_usuario_user_permissions_permission_id_3de42c14 ON public.accounts_usuario_user_permissions USING btree (permission_id);


--
-- Name: accounts_usuario_user_permissions_usuario_id_d048ad71; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_usuario_user_permissions_usuario_id_d048ad71 ON public.accounts_usuario_user_permissions USING btree (usuario_id);


--
-- Name: auditoria_r_accion_0d45cd_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auditoria_r_accion_0d45cd_idx ON public.auditoria_registroactividad USING btree (accion);


--
-- Name: auditoria_r_fecha_8d5af4_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auditoria_r_fecha_8d5af4_idx ON public.auditoria_registroactividad USING btree (fecha DESC);


--
-- Name: auditoria_r_usuario_1c2405_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auditoria_r_usuario_1c2405_idx ON public.auditoria_registroactividad USING btree (usuario_id, fecha DESC);


--
-- Name: auditoria_registroactividad_usuario_id_74428a46; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auditoria_registroactividad_usuario_id_74428a46 ON public.auditoria_registroactividad USING btree (usuario_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: casos_de_uso_casodeuso_creado_por_id_cf481468; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX casos_de_uso_casodeuso_creado_por_id_cf481468 ON public.casos_de_uso_casodeuso USING btree (creado_por_id);


--
-- Name: casos_de_uso_casodeuso_proyecto_id_a3abab89; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX casos_de_uso_casodeuso_proyecto_id_a3abab89 ON public.casos_de_uso_casodeuso USING btree (proyecto_id);


--
-- Name: casos_de_uso_historicalcas_detalle_tradicional_id_72f87d0b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX casos_de_uso_historicalcas_detalle_tradicional_id_72f87d0b ON public.casos_de_uso_historicalcasodeuso USING btree (detalle_tradicional_id);


--
-- Name: casos_de_uso_historicalcasodeuso_creado_por_id_5269a3c5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX casos_de_uso_historicalcasodeuso_creado_por_id_5269a3c5 ON public.casos_de_uso_historicalcasodeuso USING btree (creado_por_id);


--
-- Name: casos_de_uso_historicalcasodeuso_detalle_agil_id_43b8175f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX casos_de_uso_historicalcasodeuso_detalle_agil_id_43b8175f ON public.casos_de_uso_historicalcasodeuso USING btree (detalle_agil_id);


--
-- Name: casos_de_uso_historicalcasodeuso_history_date_3d916a3b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX casos_de_uso_historicalcasodeuso_history_date_3d916a3b ON public.casos_de_uso_historicalcasodeuso USING btree (history_date);


--
-- Name: casos_de_uso_historicalcasodeuso_history_user_id_66afe33e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX casos_de_uso_historicalcasodeuso_history_user_id_66afe33e ON public.casos_de_uso_historicalcasodeuso USING btree (history_user_id);


--
-- Name: casos_de_uso_historicalcasodeuso_id_a537aa42; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX casos_de_uso_historicalcasodeuso_id_a537aa42 ON public.casos_de_uso_historicalcasodeuso USING btree (id);


--
-- Name: casos_de_uso_historicalcasodeuso_proyecto_id_f27cca5d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX casos_de_uso_historicalcasodeuso_proyecto_id_f27cca5d ON public.casos_de_uso_historicalcasodeuso USING btree (proyecto_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: grupos_grupo_creado_por_id_984668eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX grupos_grupo_creado_por_id_984668eb ON public.grupos_grupo USING btree (creado_por_id);


--
-- Name: grupos_grupo_integrantes_grupo_id_bc700608; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX grupos_grupo_integrantes_grupo_id_bc700608 ON public.grupos_grupo_integrantes USING btree (grupo_id);


--
-- Name: grupos_grupo_integrantes_usuario_id_16949060; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX grupos_grupo_integrantes_usuario_id_16949060 ON public.grupos_grupo_integrantes USING btree (usuario_id);


--
-- Name: grupos_grupo_lider_id_2af30e91; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX grupos_grupo_lider_id_2af30e91 ON public.grupos_grupo USING btree (lider_id);


--
-- Name: grupos_grupo_nombre_9ffeadca_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX grupos_grupo_nombre_9ffeadca_like ON public.grupos_grupo USING btree (nombre varchar_pattern_ops);


--
-- Name: permisos_permiso_nombre_f8dfbc76_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX permisos_permiso_nombre_f8dfbc76_like ON public.permisos_permiso USING btree (nombre varchar_pattern_ops);


--
-- Name: proyectos_historicalproyecto_creado_por_id_af1a1956; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX proyectos_historicalproyecto_creado_por_id_af1a1956 ON public.proyectos_historicalproyecto USING btree (creado_por_id);


--
-- Name: proyectos_historicalproyecto_grupo_id_a4cd350a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX proyectos_historicalproyecto_grupo_id_a4cd350a ON public.proyectos_historicalproyecto USING btree (grupo_id);


--
-- Name: proyectos_historicalproyecto_history_date_8b872a04; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX proyectos_historicalproyecto_history_date_8b872a04 ON public.proyectos_historicalproyecto USING btree (history_date);


--
-- Name: proyectos_historicalproyecto_history_user_id_22ce9a73; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX proyectos_historicalproyecto_history_user_id_22ce9a73 ON public.proyectos_historicalproyecto USING btree (history_user_id);


--
-- Name: proyectos_historicalproyecto_id_56f29b25; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX proyectos_historicalproyecto_id_56f29b25 ON public.proyectos_historicalproyecto USING btree (id);


--
-- Name: proyectos_historicalproyecto_lider_id_2cc1300b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX proyectos_historicalproyecto_lider_id_2cc1300b ON public.proyectos_historicalproyecto USING btree (lider_id);


--
-- Name: proyectos_historicalproyecto_nombre_8b5129d7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX proyectos_historicalproyecto_nombre_8b5129d7 ON public.proyectos_historicalproyecto USING btree (nombre);


--
-- Name: proyectos_historicalproyecto_nombre_8b5129d7_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX proyectos_historicalproyecto_nombre_8b5129d7_like ON public.proyectos_historicalproyecto USING btree (nombre varchar_pattern_ops);


--
-- Name: proyectos_participacionproyecto_proyecto_id_6d25dac2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX proyectos_participacionproyecto_proyecto_id_6d25dac2 ON public.proyectos_participacionproyecto USING btree (proyecto_id);


--
-- Name: proyectos_participacionproyecto_rol_id_876cf6ca; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX proyectos_participacionproyecto_rol_id_876cf6ca ON public.proyectos_participacionproyecto USING btree (rol_id);


--
-- Name: proyectos_participacionproyecto_usuario_id_e8870977; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX proyectos_participacionproyecto_usuario_id_e8870977 ON public.proyectos_participacionproyecto USING btree (usuario_id);


--
-- Name: proyectos_proyecto_creado_por_id_87e4fb3b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX proyectos_proyecto_creado_por_id_87e4fb3b ON public.proyectos_proyecto USING btree (creado_por_id);


--
-- Name: proyectos_proyecto_grupo_id_31ed1cfa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX proyectos_proyecto_grupo_id_31ed1cfa ON public.proyectos_proyecto USING btree (grupo_id);


--
-- Name: proyectos_proyecto_lider_id_8ace1b31; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX proyectos_proyecto_lider_id_8ace1b31 ON public.proyectos_proyecto USING btree (lider_id);


--
-- Name: proyectos_proyecto_nombre_4e56cf5a_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX proyectos_proyecto_nombre_4e56cf5a_like ON public.proyectos_proyecto USING btree (nombre varchar_pattern_ops);


--
-- Name: requerimientos_historicalr_detalle_tradicional_id_0fbe2fdb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX requerimientos_historicalr_detalle_tradicional_id_0fbe2fdb ON public.requerimientos_historicalrequerimiento USING btree (detalle_tradicional_id);


--
-- Name: requerimientos_historicalrequerimiento_creado_por_id_940a7c2f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX requerimientos_historicalrequerimiento_creado_por_id_940a7c2f ON public.requerimientos_historicalrequerimiento USING btree (creado_por_id);


--
-- Name: requerimientos_historicalrequerimiento_detalle_agil_id_5f1a6886; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX requerimientos_historicalrequerimiento_detalle_agil_id_5f1a6886 ON public.requerimientos_historicalrequerimiento USING btree (detalle_agil_id);


--
-- Name: requerimientos_historicalrequerimiento_history_date_450b58d0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX requerimientos_historicalrequerimiento_history_date_450b58d0 ON public.requerimientos_historicalrequerimiento USING btree (history_date);


--
-- Name: requerimientos_historicalrequerimiento_history_user_id_9cbedc43; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX requerimientos_historicalrequerimiento_history_user_id_9cbedc43 ON public.requerimientos_historicalrequerimiento USING btree (history_user_id);


--
-- Name: requerimientos_historicalrequerimiento_id_1369b571; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX requerimientos_historicalrequerimiento_id_1369b571 ON public.requerimientos_historicalrequerimiento USING btree (id);


--
-- Name: requerimientos_historicalrequerimiento_proyecto_id_cc8abeed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX requerimientos_historicalrequerimiento_proyecto_id_cc8abeed ON public.requerimientos_historicalrequerimiento USING btree (proyecto_id);


--
-- Name: requerimientos_requerimiento_creado_por_id_f6d933c5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX requerimientos_requerimiento_creado_por_id_f6d933c5 ON public.requerimientos_requerimiento USING btree (creado_por_id);


--
-- Name: requerimientos_requerimiento_proyecto_id_f609e386; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX requerimientos_requerimiento_proyecto_id_f609e386 ON public.requerimientos_requerimiento USING btree (proyecto_id);


--
-- Name: requerimientos_requerimientocaso_caso_de_uso_id_cc100aa1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX requerimientos_requerimientocaso_caso_de_uso_id_cc100aa1 ON public.requerimientos_requerimientocaso USING btree (caso_de_uso_id);


--
-- Name: requerimientos_requerimientocaso_requerimiento_id_a1dc3f63; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX requerimientos_requerimientocaso_requerimiento_id_a1dc3f63 ON public.requerimientos_requerimientocaso USING btree (requerimiento_id);


--
-- Name: roles_rol_nombre_f7024258_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX roles_rol_nombre_f7024258_like ON public.roles_rol USING btree (nombre varchar_pattern_ops);


--
-- Name: roles_rol_permisos_permiso_id_a24010f3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX roles_rol_permisos_permiso_id_a24010f3 ON public.roles_rol_permisos USING btree (permiso_id);


--
-- Name: roles_rol_permisos_rol_id_d3b312b9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX roles_rol_permisos_rol_id_d3b312b9 ON public.roles_rol_permisos USING btree (rol_id);


--
-- Name: accounts_usuario_groups accounts_usuario_gro_usuario_id_8eb16911_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_usuario_groups
    ADD CONSTRAINT accounts_usuario_gro_usuario_id_8eb16911_fk_accounts_ FOREIGN KEY (usuario_id) REFERENCES public.accounts_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_usuario_groups accounts_usuario_groups_group_id_81d91a41_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_usuario_groups
    ADD CONSTRAINT accounts_usuario_groups_group_id_81d91a41_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_usuario_roles accounts_usuario_rol_usuario_id_3d21e6bb_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_usuario_roles
    ADD CONSTRAINT accounts_usuario_rol_usuario_id_3d21e6bb_fk_accounts_ FOREIGN KEY (usuario_id) REFERENCES public.accounts_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_usuario_roles accounts_usuario_roles_rol_id_d12cdecc_fk_roles_rol_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_usuario_roles
    ADD CONSTRAINT accounts_usuario_roles_rol_id_d12cdecc_fk_roles_rol_id FOREIGN KEY (rol_id) REFERENCES public.roles_rol(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_usuario_user_permissions accounts_usuario_use_permission_id_3de42c14_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_usuario_user_permissions
    ADD CONSTRAINT accounts_usuario_use_permission_id_3de42c14_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_usuario_user_permissions accounts_usuario_use_usuario_id_d048ad71_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_usuario_user_permissions
    ADD CONSTRAINT accounts_usuario_use_usuario_id_d048ad71_fk_accounts_ FOREIGN KEY (usuario_id) REFERENCES public.accounts_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auditoria_registroactividad auditoria_registroac_usuario_id_74428a46_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria_registroactividad
    ADD CONSTRAINT auditoria_registroac_usuario_id_74428a46_fk_accounts_ FOREIGN KEY (usuario_id) REFERENCES public.accounts_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: casos_de_uso_casodeuso casos_de_uso_casodeu_creado_por_id_cf481468_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.casos_de_uso_casodeuso
    ADD CONSTRAINT casos_de_uso_casodeu_creado_por_id_cf481468_fk_accounts_ FOREIGN KEY (creado_por_id) REFERENCES public.accounts_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: casos_de_uso_casodeuso casos_de_uso_casodeu_detalle_agil_id_853eb902_fk_casos_de_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.casos_de_uso_casodeuso
    ADD CONSTRAINT casos_de_uso_casodeu_detalle_agil_id_853eb902_fk_casos_de_ FOREIGN KEY (detalle_agil_id) REFERENCES public.casos_de_uso_detallecasodeusoagil(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: casos_de_uso_casodeuso casos_de_uso_casodeu_detalle_tradicional__ab5cb38f_fk_casos_de_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.casos_de_uso_casodeuso
    ADD CONSTRAINT casos_de_uso_casodeu_detalle_tradicional__ab5cb38f_fk_casos_de_ FOREIGN KEY (detalle_tradicional_id) REFERENCES public.casos_de_uso_detallecasodeusotradicional(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: casos_de_uso_casodeuso casos_de_uso_casodeu_proyecto_id_a3abab89_fk_proyectos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.casos_de_uso_casodeuso
    ADD CONSTRAINT casos_de_uso_casodeu_proyecto_id_a3abab89_fk_proyectos FOREIGN KEY (proyecto_id) REFERENCES public.proyectos_proyecto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: casos_de_uso_detallecasodeusotradicional casos_de_uso_detalle_caso_de_uso_padre_id_08c19df5_fk_casos_de_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.casos_de_uso_detallecasodeusotradicional
    ADD CONSTRAINT casos_de_uso_detalle_caso_de_uso_padre_id_08c19df5_fk_casos_de_ FOREIGN KEY (caso_de_uso_padre_id) REFERENCES public.casos_de_uso_casodeuso(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: casos_de_uso_detallecasodeusoagil casos_de_uso_detalle_caso_de_uso_padre_id_4d62b07a_fk_casos_de_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.casos_de_uso_detallecasodeusoagil
    ADD CONSTRAINT casos_de_uso_detalle_caso_de_uso_padre_id_4d62b07a_fk_casos_de_ FOREIGN KEY (caso_de_uso_padre_id) REFERENCES public.casos_de_uso_casodeuso(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: casos_de_uso_historicalcasodeuso casos_de_uso_histori_history_user_id_66afe33e_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.casos_de_uso_historicalcasodeuso
    ADD CONSTRAINT casos_de_uso_histori_history_user_id_66afe33e_fk_accounts_ FOREIGN KEY (history_user_id) REFERENCES public.accounts_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_usuario_id FOREIGN KEY (user_id) REFERENCES public.accounts_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: grupos_grupo grupos_grupo_creado_por_id_984668eb_fk_accounts_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grupos_grupo
    ADD CONSTRAINT grupos_grupo_creado_por_id_984668eb_fk_accounts_usuario_id FOREIGN KEY (creado_por_id) REFERENCES public.accounts_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: grupos_grupo_integrantes grupos_grupo_integra_usuario_id_16949060_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grupos_grupo_integrantes
    ADD CONSTRAINT grupos_grupo_integra_usuario_id_16949060_fk_accounts_ FOREIGN KEY (usuario_id) REFERENCES public.accounts_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: grupos_grupo_integrantes grupos_grupo_integrantes_grupo_id_bc700608_fk_grupos_grupo_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grupos_grupo_integrantes
    ADD CONSTRAINT grupos_grupo_integrantes_grupo_id_bc700608_fk_grupos_grupo_id FOREIGN KEY (grupo_id) REFERENCES public.grupos_grupo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: grupos_grupo grupos_grupo_lider_id_2af30e91_fk_accounts_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grupos_grupo
    ADD CONSTRAINT grupos_grupo_lider_id_2af30e91_fk_accounts_usuario_id FOREIGN KEY (lider_id) REFERENCES public.accounts_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: proyectos_historicalproyecto proyectos_historical_history_user_id_22ce9a73_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos_historicalproyecto
    ADD CONSTRAINT proyectos_historical_history_user_id_22ce9a73_fk_accounts_ FOREIGN KEY (history_user_id) REFERENCES public.accounts_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: proyectos_participacionproyecto proyectos_participac_proyecto_id_6d25dac2_fk_proyectos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos_participacionproyecto
    ADD CONSTRAINT proyectos_participac_proyecto_id_6d25dac2_fk_proyectos FOREIGN KEY (proyecto_id) REFERENCES public.proyectos_proyecto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: proyectos_participacionproyecto proyectos_participac_usuario_id_e8870977_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos_participacionproyecto
    ADD CONSTRAINT proyectos_participac_usuario_id_e8870977_fk_accounts_ FOREIGN KEY (usuario_id) REFERENCES public.accounts_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: proyectos_participacionproyecto proyectos_participacionproyecto_rol_id_876cf6ca_fk_roles_rol_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos_participacionproyecto
    ADD CONSTRAINT proyectos_participacionproyecto_rol_id_876cf6ca_fk_roles_rol_id FOREIGN KEY (rol_id) REFERENCES public.roles_rol(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: proyectos_proyecto proyectos_proyecto_creado_por_id_87e4fb3b_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos_proyecto
    ADD CONSTRAINT proyectos_proyecto_creado_por_id_87e4fb3b_fk_accounts_ FOREIGN KEY (creado_por_id) REFERENCES public.accounts_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: proyectos_proyecto proyectos_proyecto_grupo_id_31ed1cfa_fk_grupos_grupo_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos_proyecto
    ADD CONSTRAINT proyectos_proyecto_grupo_id_31ed1cfa_fk_grupos_grupo_id FOREIGN KEY (grupo_id) REFERENCES public.grupos_grupo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: proyectos_proyecto proyectos_proyecto_lider_id_8ace1b31_fk_accounts_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos_proyecto
    ADD CONSTRAINT proyectos_proyecto_lider_id_8ace1b31_fk_accounts_usuario_id FOREIGN KEY (lider_id) REFERENCES public.accounts_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: requerimientos_detallerequerimientoagil requerimientos_detal_requerimiento_padre__33d31405_fk_requerimi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_detallerequerimientoagil
    ADD CONSTRAINT requerimientos_detal_requerimiento_padre__33d31405_fk_requerimi FOREIGN KEY (requerimiento_padre_id) REFERENCES public.requerimientos_requerimiento(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: requerimientos_detallerequerimientotradicional requerimientos_detal_requerimiento_padre__9519fc8b_fk_requerimi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_detallerequerimientotradicional
    ADD CONSTRAINT requerimientos_detal_requerimiento_padre__9519fc8b_fk_requerimi FOREIGN KEY (requerimiento_padre_id) REFERENCES public.requerimientos_requerimiento(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: requerimientos_historicalrequerimiento requerimientos_histo_history_user_id_9cbedc43_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_historicalrequerimiento
    ADD CONSTRAINT requerimientos_histo_history_user_id_9cbedc43_fk_accounts_ FOREIGN KEY (history_user_id) REFERENCES public.accounts_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: requerimientos_requerimientocaso requerimientos_reque_caso_de_uso_id_cc100aa1_fk_casos_de_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_requerimientocaso
    ADD CONSTRAINT requerimientos_reque_caso_de_uso_id_cc100aa1_fk_casos_de_ FOREIGN KEY (caso_de_uso_id) REFERENCES public.casos_de_uso_casodeuso(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: requerimientos_requerimiento requerimientos_reque_creado_por_id_f6d933c5_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_requerimiento
    ADD CONSTRAINT requerimientos_reque_creado_por_id_f6d933c5_fk_accounts_ FOREIGN KEY (creado_por_id) REFERENCES public.accounts_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: requerimientos_requerimiento requerimientos_reque_detalle_agil_id_a944f32a_fk_requerimi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_requerimiento
    ADD CONSTRAINT requerimientos_reque_detalle_agil_id_a944f32a_fk_requerimi FOREIGN KEY (detalle_agil_id) REFERENCES public.requerimientos_detallerequerimientoagil(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: requerimientos_requerimiento requerimientos_reque_detalle_tradicional__04ff7e1d_fk_requerimi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_requerimiento
    ADD CONSTRAINT requerimientos_reque_detalle_tradicional__04ff7e1d_fk_requerimi FOREIGN KEY (detalle_tradicional_id) REFERENCES public.requerimientos_detallerequerimientotradicional(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: requerimientos_requerimiento requerimientos_reque_proyecto_id_f609e386_fk_proyectos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_requerimiento
    ADD CONSTRAINT requerimientos_reque_proyecto_id_f609e386_fk_proyectos FOREIGN KEY (proyecto_id) REFERENCES public.proyectos_proyecto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: requerimientos_requerimientocaso requerimientos_reque_requerimiento_id_a1dc3f63_fk_requerimi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requerimientos_requerimientocaso
    ADD CONSTRAINT requerimientos_reque_requerimiento_id_a1dc3f63_fk_requerimi FOREIGN KEY (requerimiento_id) REFERENCES public.requerimientos_requerimiento(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: roles_rol_permisos roles_rol_permisos_permiso_id_a24010f3_fk_permisos_permiso_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_rol_permisos
    ADD CONSTRAINT roles_rol_permisos_permiso_id_a24010f3_fk_permisos_permiso_id FOREIGN KEY (permiso_id) REFERENCES public.permisos_permiso(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: roles_rol_permisos roles_rol_permisos_rol_id_d3b312b9_fk_roles_rol_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_rol_permisos
    ADD CONSTRAINT roles_rol_permisos_rol_id_d3b312b9_fk_roles_rol_id FOREIGN KEY (rol_id) REFERENCES public.roles_rol(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict YVMAxB0octaTqmXrkKbnkQmbwbIuukxWTOTpsC6ZzJpE3axDe4GcKuBiO2jWNIw

