# Generated by Django 5.2.6 on 2025-10-08 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0002_proyecto_creado_por_proyecto_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRequerimientoAgil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia_usuario', models.TextField(blank=True)),
                ('criterio_aceptacion', models.TextField(blank=True)),
                ('puntos_estimados', models.PositiveIntegerField(blank=True, null=True)),
                ('sprint_asignado', models.CharField(blank=True, max_length=100)),
                ('responsable', models.CharField(blank=True, max_length=100)),
                ('estado_scrum', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRequerimientoTradicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(blank=True, max_length=50)),
                ('fuente', models.CharField(blank=True, max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('estado_validacion', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('FUNCIONAL', 'Funcional'), ('NO_FUNCIONAL', 'No funcional')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('detalle_agil', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimiento', to='requerimientos.detallerequerimientoagil', verbose_name='Detalle Ágil')),
                ('detalle_tradicional', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimiento', to='requerimientos.detallerequerimientotradicional', verbose_name='Detalle Tradicional')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos', to='proyectos.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='detallerequerimientotradicional',
            name='requerimiento_padre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_tradicional_reverse', to='requerimientos.requerimiento'),
        ),
        migrations.AddField(
            model_name='detallerequerimientoagil',
            name='requerimiento_padre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_agil_reverse', to='requerimientos.requerimiento'),
        ),
    ]
