# Generated by Django 5.2.6 on 2025-10-09 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_uso', '0001_initial'),
        ('requerimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimientoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vinculacion', models.DateTimeField(auto_now_add=True)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('caso_de_uso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_requerimientos', to='casos_de_uso.casodeuso')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_casos', to='requerimientos.requerimiento')),
            ],
            options={
                'unique_together': {('requerimiento', 'caso_de_uso')},
            },
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='casos_relacionados',
            field=models.ManyToManyField(blank=True, related_name='requerimientos_relacionados', through='requerimientos.RequerimientoCaso', to='casos_de_uso.casodeuso'),
        ),
    ]
