# Generated by Django 5.2.6 on 2025-10-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0002_requerimientocaso_requerimiento_casos_relacionados'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen adjunta (PNG, JPG, JPEG)', null=True, upload_to='requerimientos/imagenes/'),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='link_externo',
            field=models.URLField(blank=True, help_text='Enlace a recurso externo', max_length=500),
        ),
    ]
