# Generated by Django 5.2.6 on 2025-11-02 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0004_historicalrequerimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequerimiento',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrequerimiento',
            name='tipo_validador',
            field=models.CharField(blank=True, choices=[('CLIENTE', 'Cliente/Stakeholder'), ('LIDER', 'Líder de proyecto')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalrequerimiento',
            name='validado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='tipo_validador',
            field=models.CharField(blank=True, choices=[('CLIENTE', 'Cliente/Stakeholder'), ('LIDER', 'Líder de proyecto')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalrequerimiento',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('VALIDADO', 'Validado'), ('PRIORIZADO', 'Priorizado'), ('EN_PROCESO', 'En proceso'), ('TERMINADO', 'Terminado')], default='CREADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('VALIDADO', 'Validado'), ('PRIORIZADO', 'Priorizado'), ('EN_PROCESO', 'En proceso'), ('TERMINADO', 'Terminado')], default='CREADO', max_length=20),
        ),
    ]
