# Generated by Django 5.2.6 on 2025-11-02 21:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0005_historicalrequerimiento_fecha_validacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequerimiento',
            name='fecha_ultimo_rechazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrequerimiento',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Motivo del último rechazo si aplica'),
        ),
        migrations.AddField(
            model_name='historicalrequerimiento',
            name='requiere_discusion',
            field=models.BooleanField(default=False, help_text='Indica si el requerimiento necesita discusión adicional'),
        ),
        migrations.AddField(
            model_name='historicalrequerimiento',
            name='ultimo_rechazado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='fecha_ultimo_rechazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Motivo del último rechazo si aplica'),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='requiere_discusion',
            field=models.BooleanField(default=False, help_text='Indica si el requerimiento necesita discusión adicional'),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='ultimo_rechazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos_rechazados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ComentarioValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(help_text='Comentario o explicación sobre la validación/rechazo')),
                ('tipo_accion', models.CharField(choices=[('VALIDAR', 'Validar'), ('RECHAZAR', 'Rechazar'), ('RESPUESTA', 'Respuesta'), ('ACLARACION', 'Aclaraación')], help_text='Tipo de acción que representa este comentario', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_respuesta', models.BooleanField(default=False, help_text='Indica si este comentario es una respuesta a otro')),
                ('nivel_respuesta', models.PositiveIntegerField(default=0, help_text='Nivel de anidación en el hilo de conversación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_validacion', to=settings.AUTH_USER_MODEL)),
                ('comentario_padre', models.ForeignKey(blank=True, help_text='Comentario padre si es una respuesta', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='requerimientos.comentariovalidacion')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_validacion', to='requerimientos.requerimiento')),
            ],
            options={
                'verbose_name': 'Comentario de Validación',
                'verbose_name_plural': 'Comentarios de Validación',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalComentarioValidacion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('comentario', models.TextField(help_text='Comentario o explicación sobre la validación/rechazo')),
                ('tipo_accion', models.CharField(choices=[('VALIDAR', 'Validar'), ('RECHAZAR', 'Rechazar'), ('RESPUESTA', 'Respuesta'), ('ACLARACION', 'Aclaraación')], help_text='Tipo de acción que representa este comentario', max_length=20)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('es_respuesta', models.BooleanField(default=False, help_text='Indica si este comentario es una respuesta a otro')),
                ('nivel_respuesta', models.PositiveIntegerField(default=0, help_text='Nivel de anidación en el hilo de conversación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('autor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('comentario_padre', models.ForeignKey(blank=True, db_constraint=False, help_text='Comentario padre si es una respuesta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='requerimientos.comentariovalidacion')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requerimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='requerimientos.requerimiento')),
            ],
            options={
                'verbose_name': 'historical Comentario de Validación',
                'verbose_name_plural': 'historical Comentarios de Validación',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
