# Generated by Django 5.2.6 on 2025-11-02 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0006_historicalrequerimiento_fecha_ultimo_rechazo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallerequerimientoagil',
            name='estado_scrum',
        ),
        migrations.RemoveField(
            model_name='detallerequerimientoagil',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='detallerequerimientoagil',
            name='sprint_asignado',
        ),
    ]
