# Generated by Django 5.2.6 on 2025-11-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0007_remove_agile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimientoagil',
            name='prioridad',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
