# Generated by Django 5.2.6 on 2025-11-04 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0008_detallerequerimientoagil_prioridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrequerimiento',
            name='detalle_agil',
        ),
        migrations.RemoveField(
            model_name='historicalrequerimiento',
            name='detalle_tradicional',
        ),
        migrations.RemoveField(
            model_name='requerimiento',
            name='detalle_agil',
        ),
        migrations.RemoveField(
            model_name='requerimiento',
            name='detalle_tradicional',
        ),
        migrations.AlterField(
            model_name='detallerequerimientoagil',
            name='requerimiento_padre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_agil', to='requerimientos.requerimiento'),
        ),
        migrations.AlterField(
            model_name='detallerequerimientotradicional',
            name='requerimiento_padre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_tradicional', to='requerimientos.requerimiento'),
        ),
    ]
