# Generated by Django 5.2.6 on 2025-11-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0009_remove_historicalrequerimiento_detalle_agil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequerimiento',
            name='tipo',
            field=models.CharField(choices=[('FUNCIONAL', 'Funcional'), ('NO_FUNCIONAL', 'No funcional'), ('SISTEMA', 'Sistema')], max_length=20),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='tipo',
            field=models.CharField(choices=[('FUNCIONAL', 'Funcional'), ('NO_FUNCIONAL', 'No funcional'), ('SISTEMA', 'Sistema')], max_length=20),
        ),
    ]
