# Generated by Django 5.2.6 on 2025-11-04 20:02

from django.db import migrations, models


def actualizar_estado_creado_a_borrador(apps, schema_editor):
    """Migración de datos: cambiar todos los estados CREADO a BORRADOR"""
    Requerimiento = apps.get_model('requerimientos', 'Requerimiento')
    HistoricalRequerimiento = apps.get_model('requerimientos', 'HistoricalRequerimiento')
    
    # Actualizar Requerimiento
    Requerimiento.objects.filter(estado='CREADO').update(estado='BORRADOR')
    
    # Actualizar HistoricalRequerimiento
    HistoricalRequerimiento.objects.filter(estado='CREADO').update(estado='BORRADOR')


def revertir_borrador_a_creado(apps, schema_editor):
    """Migración reversa: cambiar todos los estados BORRADOR a CREADO"""
    Requerimiento = apps.get_model('requerimientos', 'Requerimiento')
    HistoricalRequerimiento = apps.get_model('requerimientos', 'HistoricalRequerimiento')
    
    # Revertir Requerimiento
    Requerimiento.objects.filter(estado='BORRADOR').update(estado='CREADO')
    
    # Revertir HistoricalRequerimiento
    HistoricalRequerimiento.objects.filter(estado='BORRADOR').update(estado='CREADO')


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0010_agregar_tipo_sistema'),
    ]

    operations = [
        migrations.RunPython(
            actualizar_estado_creado_a_borrador,
            revertir_borrador_a_creado
        ),
        migrations.AlterField(
            model_name='historicalrequerimiento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('VALIDADO', 'Validado'), ('PRIORIZADO', 'Priorizado'), ('EN_PROCESO', 'En proceso'), ('TERMINADO', 'Terminado')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('VALIDADO', 'Validado'), ('PRIORIZADO', 'Priorizado'), ('EN_PROCESO', 'En proceso'), ('TERMINADO', 'Terminado')], default='BORRADOR', max_length=20),
        ),
    ]
