# Generated by Django 5.2.6 on 2025-11-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0011_cambiar_creado_a_borrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariovalidacion',
            name='tipo_comentario',
            field=models.CharField(choices=[('DISCUSION_INTERNA', 'Discusión Interna'), ('VALIDACION_CLIENTE', 'Validación con Cliente'), ('IMPLEMENTACION', 'Implementación')], default='DISCUSION_INTERNA', help_text='Contexto del comentario: interno del equipo, con cliente, o implementación', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcomentariovalidacion',
            name='tipo_comentario',
            field=models.CharField(choices=[('DISCUSION_INTERNA', 'Discusión Interna'), ('VALIDACION_CLIENTE', 'Validación con Cliente'), ('IMPLEMENTACION', 'Implementación')], default='DISCUSION_INTERNA', help_text='Contexto del comentario: interno del equipo, con cliente, o implementación', max_length=20),
        ),
        migrations.AlterField(
            model_name='comentariovalidacion',
            name='tipo_accion',
            field=models.CharField(choices=[('VALIDAR', 'Validar'), ('RECHAZAR', 'Rechazar'), ('RESPUESTA', 'Respuesta'), ('ACLARACION', 'Aclaración')], help_text='Tipo de acción que representa este comentario', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcomentariovalidacion',
            name='tipo_accion',
            field=models.CharField(choices=[('VALIDAR', 'Validar'), ('RECHAZAR', 'Rechazar'), ('RESPUESTA', 'Respuesta'), ('ACLARACION', 'Aclaración')], help_text='Tipo de acción que representa este comentario', max_length=20),
        ),
    ]
