# Generated by Django 5.2.6 on 2025-11-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0012_agregar_tipo_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='dependencias',
            field=models.ManyToManyField(blank=True, help_text='Requerimientos de los que depende este requerimiento', related_name='dependientes', to='requerimientos.requerimiento'),
        ),
    ]
