# Generated by Django 5.2.8 on 2025-11-16 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_proyecto_clientes'),
        ('requerimientos', '0013_requerimiento_dependencias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=100)),
                ('es_predefinida', models.BooleanField(default=False, help_text='Indica si es una categoría del sistema')),
                ('veces_utilizada', models.PositiveIntegerField(default=0, help_text='Contador de uso para ordenar por popularidad')),
                ('es_favorita', models.BooleanField(default=False, help_text='Marcada como favorita por el líder')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_requerimiento', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Categoría de Requerimiento',
                'verbose_name_plural': 'Categorías de Requerimientos',
                'ordering': ['-es_favorita', '-veces_utilizada', 'nombre'],
                'unique_together': {('proyecto', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='FuenteRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la fuente del requerimiento', max_length=255)),
                ('es_predefinida', models.BooleanField(default=False, help_text='Indica si es una fuente del sistema')),
                ('veces_utilizada', models.PositiveIntegerField(default=0, help_text='Contador de uso para ordenar por popularidad')),
                ('es_favorita', models.BooleanField(default=False, help_text='Marcada como favorita por el líder')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuentes_requerimiento', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Fuente de Requerimiento',
                'verbose_name_plural': 'Fuentes de Requerimientos',
                'ordering': ['-es_favorita', '-veces_utilizada', 'nombre'],
                'unique_together': {('proyecto', 'nombre')},
            },
        ),
    ]
