# Generated by Django 5.2.8 on 2025-11-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0014_categoriarequerimiento_fuenterequerimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariovalidacion',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen adjunta al comentario (PNG, JPG, JPEG)', null=True, upload_to='comentarios/imagenes/'),
        ),
        migrations.AddField(
            model_name='comentariovalidacion',
            name='link_externo',
            field=models.URLField(blank=True, help_text='Enlace externo relacionado con el comentario', max_length=500),
        ),
        migrations.AddField(
            model_name='historicalcomentariovalidacion',
            name='imagen',
            field=models.TextField(blank=True, help_text='Imagen adjunta al comentario (PNG, JPG, JPEG)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomentariovalidacion',
            name='link_externo',
            field=models.URLField(blank=True, help_text='Enlace externo relacionado con el comentario', max_length=500),
        ),
    ]
