# Generated by Django 5.2.6 on 2025-10-10 14:40

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_rol_permisos_alter_usuario_roles_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', accounts.models.UsuarioManager()),
            ],
        ),
    ]
