# Generated by Django 5.2.6 on 2025-10-21 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('CREATE_USER', 'Creación de usuario'), ('UPDATE_USER', 'Modificación de usuario'), ('DELETE_USER', 'Eliminación de usuario'), ('CHANGE_ROLE', 'Cambio de rol'), ('CREATE_PROJECT', 'Creación de proyecto'), ('DELETE_PROJECT', 'Eliminación de proyecto'), ('CREATE_GROUP', 'Creación de grupo'), ('DELETE_GROUP', 'Eliminación de grupo'), ('ADMIN_ACTION', 'Acción administrativa')], max_length=20)),
                ('descripcion', models.TextField()),
                ('detalles', models.JSONField(blank=True, help_text='Detalles adicionales en formato JSON', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='auditoria_r_fecha_8d5af4_idx'), models.Index(fields=['usuario', '-fecha'], name='auditoria_r_usuario_1c2405_idx'), models.Index(fields=['accion'], name='auditoria_r_accion_0d45cd_idx')],
            },
        ),
    ]
