# Generated by Django 5.2.6 on 2025-10-08 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0002_proyecto_creado_por_proyecto_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoDeUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_de_uso', to='proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCasoDeUsoAgil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia_usuario', models.TextField(blank=True)),
                ('criterio_aceptacion', models.TextField(blank=True)),
                ('responsable', models.CharField(blank=True, max_length=100)),
                ('estado_scrum', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('caso_de_uso_padre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_agil_reverse', to='casos_de_uso.casodeuso')),
            ],
        ),
        migrations.AddField(
            model_name='casodeuso',
            name='detalle_agil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caso_de_uso', to='casos_de_uso.detallecasodeusoagil', verbose_name='Detalle Ágil'),
        ),
        migrations.CreateModel(
            name='DetalleCasoDeUsoTradicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_principal', models.CharField(blank=True, max_length=255)),
                ('precondiciones', models.TextField(blank=True)),
                ('flujo_principal', models.TextField(blank=True)),
                ('flujo_alternativo', models.TextField(blank=True)),
                ('postcondiciones', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('caso_de_uso_padre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_tradicional_reverse', to='casos_de_uso.casodeuso')),
            ],
        ),
        migrations.AddField(
            model_name='casodeuso',
            name='detalle_tradicional',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caso_de_uso', to='casos_de_uso.detallecasodeusotradicional', verbose_name='Detalle Tradicional'),
        ),
    ]
