# Generated by Django 5.2.6 on 2025-10-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_uso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casodeuso',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen adjunta (PNG, JPG, JPEG)', null=True, upload_to='casos_de_uso/imagenes/'),
        ),
        migrations.AddField(
            model_name='casodeuso',
            name='link_externo',
            field=models.URLField(blank=True, help_text='Enlace a recurso externo', max_length=500),
        ),
    ]
