# Generated by Django 5.2.6 on 2025-11-02 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_uso', '0003_historicalcasodeuso'),
    ]

    operations = [
    ]
