# Generated by Django 5.2.6 on 2025-11-02 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_uso', '0004_clean_migration_state'),
        ('requerimientos', '0006_historicalrequerimiento_fecha_ultimo_rechazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casodeuso',
            name='requerimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_de_uso', to='requerimientos.requerimiento'),
        ),
        migrations.AddField(
            model_name='historicalcasodeuso',
            name='requerimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='requerimientos.requerimiento'),
        ),
    ]
