# Generated by Django 5.2.8 on 2025-11-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_uso', '0005_casodeuso_requerimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casodeuso',
            name='identificador',
            field=models.CharField(blank=True, help_text='Identificador único del caso de uso (ej: CU-001)', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcasodeuso',
            name='identificador',
            field=models.CharField(blank=True, help_text='Identificador único del caso de uso (ej: CU-001)', max_length=20),
        ),
    ]
