# Generated by Django 5.2.6 on 2025-11-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_uso', '0004_detallecasodeusoagil_prioridad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecasodeusoagil',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='detallecasodeusotradicional',
            name='prioridad',
        ),
    ]
