# Generated by Django 5.2.8 on 2025-11-18 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casos_de_uso', '0007_historicaldetallecasodeusoagil_and_more'),
    ]

    operations = [
    ]
