# Generated by Django 5.2.6 on 2025-10-19 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_grupo_lider'),
        ('proyectos', '0002_proyecto_creado_por_proyecto_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='grupos.grupo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='metodologia',
            field=models.CharField(choices=[('TRADICIONAL', 'Tradicional'), ('AGIL', 'Ágil')], default='AGIL', max_length=20),
        ),
    ]
