# Generated by Django 5.2.6 on 2025-10-19 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_grupo_lider'),
        ('proyectos', '0003_proyecto_grupo_alter_proyecto_metodologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='grupos.grupo'),
        ),
    ]
