# Generated by Django 5.2.6 on 2025-10-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alter_proyecto_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='metodologia',
            field=models.CharField(blank=True, choices=[('TRADICIONAL', 'Tradicional'), ('AGIL', 'Ágil')], max_length=20, null=True),
        ),
    ]
