# Generated by Django 5.2.6 on 2025-11-05 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_historicalproyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='clientes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'roles__nombre': 'Stakeholder'}, related_name='proyectos_como_cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
