# Generated by Django 5.2.8 on 2025-11-17 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_proyecto_clientes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='visitantes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'roles__nombre': 'Visitante'}, related_name='proyectos_como_visitante', to=settings.AUTH_USER_MODEL),
        ),
    ]
