# Generated by Django 5.2.6 on 2025-10-23
# Migración para eliminar modelo AccionUsuario obsoleto
# La funcionalidad ahora está en auditoria.RegistroActividad

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccionUsuario',
        ),
    ]
